owner: 9min
repo: upptime
sites:
  - name: wedding-invitation
    url: https://9min.github.io/wedding-invitation/
  - name: Secret Site
    url: $SECRET_SITE
  - name: Broken Site
    url: https://gumin123.co.kr
  - name: Agit
    url: https://kakaomobility.agit.in/
  - name: Jira
    url: https://jira.daumkakao.com/
assignees:
  - 9min
status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 9min's status
  introTitle: 9min's site status
  introMessage: This is a 9min's site status page
  navbar:
    - title: GitHub
      href: https://github.com/9min
notifications:
  - type: slack
    channel: G01E6DAAMSS
