owner: 9min
repo: upptime
sites:
  - name: stock-streaming-viewer
    url: https://9min.github.io/stock-streaming-viewer/
  - name: 9min-wedding-invitation
    url: https://9min.github.io/wedding-invitation/
  - name: joohee-wedding-invitation
    url: https://joohee0928.github.io/wedding-invitation/
  - name: Secret Site
    url: $SECRET_SITE
assignees:
  - 9min
status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: 9min's status
  introTitle: 9min's site status
  introMessage: This is a 9min's site status page
  navbar:
    - title: GitHub
      href: https://github.com/9min
notifications:
  NOTIFICATION_SLACK: true
  NOTIFICATION_SLACK_WEBHOOK: true
  NOTIFICATION_SLACK_WEBHOOK_URL: ${{ secrets.NOTIFICATION_SLACK_WEBHOOK_URL }}
